[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.virtualenv']

[phases.install]
cmds = ['python -m venv venv', 'source venv/bin/activate && pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'source venv/bin/activate && gunicorn --bind 0.0.0.0:$PORT app:app'
